// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6OkWF0At2Zz05i0xP_J5vk1WYYgWkrA',
    appId: '1:907959142478:web:756b294bb843da164e1b1f',
    messagingSenderId: '907959142478',
    projectId: 'belanja-2',
    authDomain: 'belanja-2.firebaseapp.com',
    databaseURL: 'https://belanja-2-default-rtdb.firebaseio.com',
    storageBucket: 'belanja-2.appspot.com',
    measurementId: 'G-XHXZ9ZDQJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1y-GUHYCnUrr4RcoPHnM5CdGuOOrNyfg',
    appId: '1:907959142478:android:5dfa4c19e168f0854e1b1f',
    messagingSenderId: '907959142478',
    projectId: 'belanja-2',
    databaseURL: 'https://belanja-2-default-rtdb.firebaseio.com',
    storageBucket: 'belanja-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApznTEzaLGKyAX_SEKe4TU4DG-25-vmi4',
    appId: '1:907959142478:ios:ec4995d83243f1504e1b1f',
    messagingSenderId: '907959142478',
    projectId: 'belanja-2',
    databaseURL: 'https://belanja-2-default-rtdb.firebaseio.com',
    storageBucket: 'belanja-2.appspot.com',
    iosBundleId: 'com.example.daftarBelanja2uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApznTEzaLGKyAX_SEKe4TU4DG-25-vmi4',
    appId: '1:907959142478:ios:8e9a986dc57cb6b34e1b1f',
    messagingSenderId: '907959142478',
    projectId: 'belanja-2',
    databaseURL: 'https://belanja-2-default-rtdb.firebaseio.com',
    storageBucket: 'belanja-2.appspot.com',
    iosBundleId: 'com.example.daftarBelanja2uts.RunnerTests',
  );
}
